<?php

namespace GAHelloWorld;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../src/GAHelloWorld/Population.php';

/**
 * Test class for Population.
 * Generated by PHPUnit on 2011-04-16 at 07:54:42.
 */
class PopulationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Population
     */
    protected $population;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->population = new Population('Hello, World!');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testEvolve().
     */
    public function testEvolve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
